import type { Article, MapMarker, SightingType } from '@/types'

export const demoArticles: Article[] = [
  {
    id: 'a1',
    title: 'El Incidente de Roswell: 75 Años Después',
    slug: 'incidente-roswell-75-anos-despues',
    content: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Resumen del caso Roswell...' }] }] },
    excerpt: 'Análisis del caso OVNI más famoso de la historia',
    coverImage: '/globe.svg',
    tags: ['roswell', 'ovni', 'historia'],
    metaTitle: 'Roswell 75 años después',
    metaDescription: 'Análisis histórico del incidente de Roswell',
    status: 'PUBLISHED',
    views: 12034,
    likes: 423,
    featured: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
    publishedAt: new Date('2023-01-02'),
    authorId: 'u1',
    categoryId: 'c1',
  },
  {
    id: 'a2',
    title: 'Pentagon UAP Videos: Scientific Analysis',
    slug: 'pentagon-uap-videos-scientific-analysis',
    content: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Análisis de videos del Pentágono...' }] }] },
    excerpt: 'Desglose del material oficial UAP',
    coverImage: '/window.svg',
    tags: ['uap', 'pentagon', 'science'],
    status: 'PUBLISHED',
    views: 8911,
    likes: 301,
    featured: false,
    createdAt: new Date('2023-05-12'),
    updatedAt: new Date('2024-02-20'),
    publishedAt: new Date('2023-05-13'),
    authorId: 'u2',
    categoryId: 'c2',
  },
]

export const demoMarkers: MapMarker[] = [
  {
    id: 'm1',
    position: [33.3943, -104.5230],
    type: 'CRAFT' as SightingType,
    title: 'Incidente de Roswell',
    description: 'Supuesto accidente de nave extraterrestre en 1947',
    credibility: 8,
    verified: false,
    dateOccurred: new Date('1947-07-08'),
  },
  {
    id: 'm2',
    position: [51.5074, -0.1278],
    type: 'LIGHTS' as SightingType,
    title: 'Luces sobre Londres',
    description: 'Múltiples reportes de luces moviéndose a gran velocidad',
    credibility: 6,
    verified: true,
    dateOccurred: new Date('2021-10-11'),
  },
  {
    id: 'm3',
    position: [9.7489, -83.7534],
    type: 'DISK' as SightingType,
    title: 'Objeto discoidal en Costa Rica',
    description: 'Objeto metálico con movimiento errático',
    credibility: 7,
    verified: true,
    dateOccurred: new Date('2022-03-05'),
  },
]
