[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  # Add any environment variables defaults here if desired. Set real values in Netlify UI.
  # NEXT_PUBLIC_SUPABASE_URL = ""
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
